[project]
name = "t2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "minisom>=2.3.5",
    "pandas>=2.3.0",
    "requests>=2.32.3",
    "seaborn>=0.13.2",
    "xlrd==1.2.0",
]
