[project]
name = "t1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=0.26.0",
    "colorama>=0.4.6",
    "datasets>=3.6.0",
    "evaluate>=0.4.3",
    "flask>=1.1.2",
    "ipykernel>=6.29.5",
    "label-studio>=1.18.0",
    "label-studio-ml>=1.0.9",
    "label-studio-sdk>=1.0.12",
    "matplotlib>=3.10.3",
    "num2words>=0.5.14",
    "pillow>=11.2.1",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "semver>=3.0.4",
    "seqeval>=1.2.2",
    "torch>=2.6.0",
    "transformers>=4.52.3",
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }
